### ISSUE TITLE
Previous blog archives links 404ing

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentries.org#292]
Congratulations on the new website, it looks great! 

I noticed that links to previous blog posts are 404ing, e.g. anything with https://carpentries.org/blog/archive/

So, that means any historical links to previous blog posts aren't working. 

One example is this [HPC Carpentry post](https://www.hpc-carpentry.org/blog/2024/07/hpc-carpentry-incubation-announcement.html), links to the cross-post, and that [cross-post link](https://carpentries.org/blog/2024/07/hpc-carpentry-incubation-announcement/) isn't working.

**Comment by maneesha** [comment]
Thanks for your observation @tracykteal.  We have changed how our blog is set up, and I have been working on fixing some issues that came from it.  I am keeping your issue open as we do still have some blog posts to correct, but most of them should now be working.

**Comment by maneesha** [comment]
These should all be fixed now so I am closing this issue.  Please feel free to open another issue if any other blog links do not work.

**Comment by tracykteal** [comment]
Amazing! Thanks so much. A very nice transition to the new website.
