### ISSUE TITLE
Info on Carpentries Slack missing

### ISSUE THREAD

**Issue by anenadic** [carpentries/carpentries.org#295]
Info on joining the general Carpentries Slack (not the regional communities's Slack) is missing from all community/get-conntected/contact-us pages.

https://carpentries.org/community/get-involved/
https://carpentries.org/community/get-connected/
https://carpentries.org/community
https://carpentries.org/about-us/contact/

**Comment by maneesha** [comment]
Thanks for your suggestion @anenadic. 
Tagging @OscarSiba for recommendations on where to include this information.

**Comment by OscarSiba** [comment]
Thank you so much @anenadic!  

@maneesha, please add as follows: 

- [x] On our [Contact us page](https://carpentries.org/about-us/contact/), just below "By email" add: 

**On Slack**

- General Slack Channel

- [x] And then, on our [Get involved page](https://carpentries.org/community/get-involved/), as a first listed item after the sentence "We also keep our community strong and connected through meetups (virtual and in-person) and interest-specific mailing lists", please hyperlink to our [General Carpentries Slack channel].

**Comment by maneesha** [comment]
Addressed with #303
