### ISSUE TITLE
Case insentitive URLs 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org#300]
Hugo treats URLs as case sensitive.  We should disable this.
See https://discourse.gohugo.io/t/disable-hugo-case-sensitive-url-matching/2498

**Comment by maneesha** [comment]
Note this solution will support **new** urls but does not address existing urls.  That may need to be handled at the server level.

**Comment by maneesha** [comment]
@froggleston  Can we include this in our server side redirects?

**Comment by froggleston** [comment]
Is there a link to why it won't work for existing URLs?

**Comment by froggleston** [comment]
I've implemented a redirect lambda as per the beta handbook, and it will now automatically force uppercase to lowercase in the request URI. Tested and seems to be working.
