### ISSUE TITLE
DC and LC have an incorrect hyperlink in /workshops

### ISSUE THREAD

**Issue by josenino95** [carpentries/carpentries.org#302]
Both in [https://datacarpentry.org/workshops/](https://datacarpentry.org/workshops/) and [https://librarycarpentry.org/workshops/](https://librarycarpentry.org/workshops/) there's an incorrect link in the fourth item "About Carpentries workshops". The former links to "https://carpentries.orgworkshops/" (missing slash) and the latter to "https://carpentries.org//workshops" (extra slash), where I think the correct one is "https://carpentries.org/workshops".

**Comment by maneesha** [comment]
Thanks @josenino95 for spotting this.
These links have been fixed. Please feel free to raise issues for anything else that doesn't look right.
