### ISSUE TITLE
Grammar of front page banner text

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org#304]
On our three lesson program sites, we refer to the lesson program in third person.  For example, on the [SWC site](https://software-carpentry.org/), we say "Software Carpentry is a lesson program within The Carpentries teaching basic lab skills for research computing."

However, on The Carpentries site, we state the banner text in first person (plural):  "We teach foundational coding and data science skills to researchers worldwide."

Should the voice be consistent?  I have no strong feelings about this other than preferring consistency. Opening this for non-urgent discussion.

**Comment by froggleston** [comment]
I think this is fine - the Carpentries as "we" the organisation, and each of the lesson programs as a "thing" within that organisation?

**Comment by OscarSiba** [comment]
While it is fine as is, I think we should change to "The Carpentries teaches...". It has more impact (and consistency) that way.

**Comment by maneesha** [comment]
Addressed with #312
