### ISSUE TITLE
Navigating through sections in a page

### ISSUE THREAD

**Issue by josenino95** [carpentries/carpentries.org#305]
Personally, I don't find intuitive the way that users should navigate through the different sections of a page. For example, if from the homepage carpentries.org I go to [Support us > Membership](https://carpentries.org/support/membership/), I land in the "Membership" page. From there I could navigate to "Membership FAQ" and "Current Members". However, it's not clear that these other sections are clickable, as they are not underlined like conventional hyperlinks, or they not clearly show that I'm in section 1 of 3 possible.

Let me know if I haven't explained clearly the issue I'm raising here. This is more a personal opinion on the looks and navigation of the website, so maybe there are other design choices behind the current website style that I don't know of.

Here is an image of the example I gave in the Membership page.
![image](https://github.com/user-attachments/assets/2bf4a5c1-2e54-4a72-ab3b-f346dc2dae25)

**Comment by OscarSiba** [comment]
Thank you @josenino95 for your feedback. We have spent some time assessing how we could incorporate what you are suggesting, but unfortunately doing so will entail a somewhat involved change to our design that is not easy to implement at the moment. But thank you for sharing this, and if you come across any more suggestions, please continue to send them our way.
