### ISSUE TITLE
Possibility of adding a search feature in the Incubator webpage

### ISSUE THREAD

**Issue by josenino95** [carpentries/carpentries.org#306]
The "search lessons" feature at the right of the [lessons page](https://carpentries.org/lessons/) is really nice. Would it be possible to have the same feature in the [Community Developed Lessons page](https://carpentries.org/lesson-development/community-lessons/)?

**Comment by maneesha** [comment]
Thanks for your suggestion @josenino95 
I agree, and this is a feature we are considering for a future release.  Closing this as we have as issue open for this in the [website's theme](https://github.com/carpentries/carpentries-hugo-theme/issues/53).
