### ISSUE TITLE
Link to the Carpentries Handbook and pad-of-pads from a more prominent place

### ISSUE THREAD

**Issue by jevbelikov** [carpentries/carpentries.org#329]
I couldn't find any links to the Handbook(s) or pad-of-pads on the new Carpentries page. 
Could they be added or displayed more prominently? Or was it a deliberate decision not do so?

**Comment by maneesha** [comment]
Thanks for your question @jevbelikov 

The [pad-of-pads](https://pad.carpentries.org/pad-of-pads) is referenced throughout our [handbook](https://docs.carpentries.org/).  

The handbook is included as a volunteer resource in the top menu.  
![image](https://github.com/user-attachments/assets/37242942-0691-449b-88f6-590afdd39135)
