### ISSUE TITLE
Map of past and upcoming workshops

### ISSUE THREAD

**Issue by jevbelikov** [carpentries/carpentries.org#330]
It would be nice to have a geospatial visualisation of past and upcoming workshops.

**Comment by maneesha** [comment]
This is included in our [workshops map feed](https://feeds.carpentries.org/plot_workshops_map.svg) (as part of our [general feeds](https://feeds.carpentries.org/)).

**Comment by jevbelikov** [comment]
Thanks, that's useful. Are they linked from somewhere on the website or does on need to use 'Search' to find it?
